services:
  # Backend API Service
  - type: web
    name: upload-management-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: PORT
        value: 10000
      - key: UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 10485760

  # Frontend Static Site
  - type: web
    name: upload-management-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install --include=dev && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://upload-management-backend.onrender.com 