services:
  # Backend API Service
  - type: web
    name: upload-management-backend
    env: node
    plan: free
    nodeVersion: 20
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: PORT
        value: 10000
      - key: UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_ORIGINS
        value: https://upload-management-frontend.onrender.com,https://docky-frontend-uufo.onrender.com

  # Frontend Static Site (Primary Configuration)
  - type: static
    name: upload-management-frontend
    plan: free
    rootDir: frontend
    buildCommand: npm install --production=false && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://docky-backend-b9a1.onrender.com

  # Frontend Web Service (Alternative Configuration)
  - type: web
    name: upload-management-frontend-web
    env: node
    plan: free
    nodeVersion: 20
    rootDir: frontend
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: VITE_API_URL
        value: https://docky-backend-b9a1.onrender.com
      - key: PORT
        value: 10001
